project:
  type: website

website:
  title: "`meta` Shortcodes for Precise Includes"
  repo-url: https://github.com/quarto-dev/quarto-examples
  repo-subdir: websites/quarto-meta-includes
  repo-actions: [source]
  navbar: 
    left:
      - href: index.qmd
        text: "Home"
      - href: new-york.qmd
      - href: pa.qmd
      


format:
  html:
    theme: yeti
    css: styles.css
    toc: true



